### ISSUE TITLE
EntityBendingDeath NullPointerException

### ISSUE THREAD

**Issue by plushmonkey** [ProjectKorra/ProjectKorra#973]
Version: ProjectKorra 1.8.7

https://pastebin.com/AczuVZCy

The event's attacker is used without being checked if it's null. It can be null when an entity is killed by FireDamageTimer tick. 

FireDamageTimer grabs the first Fire ability stored and uses it as the damage ability, which has a null player stored in it, so the EntityBendingDeathEvent uses that null player as the attacker. I think this is the reason, but I didn't look into it too much.

You can replicate the exception by killing someone with a FireDamageTimer tick. The easiest way to do it is to hit a parrot with FireWheel with the default config. They need to die from the burn, not the initial attack.

**Comment by 0ct0ber** [comment]
I'm getting the same error at line 741.

**Comment by Varhagna** [comment]
@0ct0ber This issue was created nearly a year ago, have you attempted using a newer version and checking if the problem persists?

**Comment by 0ct0ber** [comment]
@Varhagna It's using Spigot 1.12.2 and ProjectKorra 1.8.7.

**Comment by xNuminousx** [comment]
> @Varhagna It's using Spigot 1.12.2 and ProjectKorra 1.8.7.
Yea theres been an update since this issue.

**Comment by Varhagna** [comment]
@0ct0ber @xNuminousx This issue has been fixed in the later version by @PhanaticD

**Comment by 0ct0ber** [comment]
@Varhagna @xNuminousx still not a 1.12 port made available yet though.

**Comment by Varhagna** [comment]
Can't find the PR which fixed this, we really need to have better documentation for PR names.
